require('typescript-require')

const { screens } = require('./src/config/screens.ts')

module.exports = {
  content: ['./src/{pages,app,features}/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      screens: {
        ...screens,
      },
      colors: {
        black: '#000000',
        white: '#ffffff',

        blackA: {
          DEFAULT: 'var(--blackA9)',
          1: 'var(--blackA1)',
          2: 'var(--blackA2)',
          3: 'var(--blackA3)',
          4: 'var(--blackA4)',
          5: 'var(--blackA5)',
          6: 'var(--blackA6)',
          7: 'var(--blackA7)',
          8: 'var(--blackA8)',
          9: 'var(--blackA9)',
          10: 'var(--blackA10)',
          11: 'var(--blackA11)',
          12: 'var(--blackA12)',
        },

        whiteA: {
          DEFAULT: 'var(--whiteA9)',
          1: 'var(--whiteA1)',
          2: 'var(--whiteA2)',
          3: 'var(--whiteA3)',
          4: 'var(--whiteA4)',
          5: 'var(--whiteA5)',
          6: 'var(--whiteA6)',
          7: 'var(--whiteA7)',
          8: 'var(--whiteA8)',
          9: 'var(--whiteA9)',
          10: 'var(--whiteA10)',
          11: 'var(--whiteA11)',
          12: 'var(--whiteA12)',
        },

        gray: {
          DEFAULT: 'var(--slate9)',
          1: 'var(--slate1)',
          2: 'var(--slate2)',
          3: 'var(--slate3)',
          4: 'var(--slate4)',
          5: 'var(--slate5)',
          6: 'var(--slate6)',
          7: 'var(--slate7)',
          8: 'var(--slate8)',
          9: 'var(--slate9)',
          10: 'var(--slate10)',
          11: 'var(--slate11)',
          12: 'var(--slate12)',
        },

        grayA: {
          DEFAULT: 'var(--slateA9)',
          1: 'var(--slateA1)',
          2: 'var(--slateA2)',
          3: 'var(--slateA3)',
          4: 'var(--slateA4)',
          5: 'var(--slateA5)',
          6: 'var(--slateA6)',
          7: 'var(--slateA7)',
          8: 'var(--slateA8)',
          9: 'var(--slateA9)',
          10: 'var(--slateA10)',
          11: 'var(--slateA11)',
          12: 'var(--slateA12)',
        },

        crimson: {
          DEFAULT: 'var(--crimson9)',
          1: 'var(--crimson1)',
          2: 'var(--crimson2)',
          3: 'var(--crimson3)',
          4: 'var(--crimson4)',
          5: 'var(--crimson5)',
          6: 'var(--crimson6)',
          7: 'var(--crimson7)',
          8: 'var(--crimson8)',
          9: 'var(--crimson9)',
          10: 'var(--crimson10)',
          11: 'var(--crimson11)',
          12: 'var(--crimson12)',
        },

        green: {
          DEFAULT: 'var(--green9)',
          1: 'var(--green1)',
          2: 'var(--green2)',
          3: 'var(--green3)',
          4: 'var(--green4)',
          5: 'var(--green5)',
          6: 'var(--green6)',
          7: 'var(--green7)',
          8: 'var(--green8)',
          9: 'var(--green9)',
          10: 'var(--green10)',
          11: 'var(--green11)',
          12: 'var(--green12)',
        },

        indigo: {
          DEFAULT: 'var(--indigo9)',
          1: 'var(--indigo1)',
          2: 'var(--indigo2)',
          3: 'var(--indigo3)',
          4: 'var(--indigo4)',
          5: 'var(--indigo5)',
          6: 'var(--indigo6)',
          7: 'var(--indigo7)',
          8: 'var(--indigo8)',
          9: 'var(--indigo9)',
          10: 'var(--indigo10)',
          11: 'var(--indigo11)',
          12: 'var(--indigo12)',
        },

        violet: {
          DEFAULT: 'var(--violet9)',
          1: 'var(--violet1)',
          2: 'var(--violet2)',
          3: 'var(--violet3)',
          4: 'var(--violet4)',
          5: 'var(--violet5)',
          6: 'var(--violet6)',
          7: 'var(--violet7)',
          8: 'var(--violet8)',
          9: 'var(--violet9)',
          10: 'var(--violet10)',
          11: 'var(--violet11)',
          12: 'var(--violet12)',
        },
      },
      typography: ({ theme }) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.gray[12]'),
            '--tw-prose-headings': theme('colors.gray[12]'),
            '--tw-prose-lead': theme('colors.gray[8]'),
            '--tw-prose-links': theme('colors.blue[12]'),
            '--tw-prose-bold': theme('colors.gray[12]'),
            '--tw-prose-counters': theme('colors.gray[12]'),
            '--tw-prose-bullets': theme('colors.gray[12]'),
            '--tw-prose-hr': theme('colors.gray[6]'),
            '--tw-prose-quotes': theme('colors.gray[12]'),
            '--tw-prose-quote-borders': theme('colors.gray[7]'),
            '--tw-prose-captions': theme('colors.gray[8]'),
            '--tw-prose-code': theme('colors.gray[12]'),
            '--tw-prose-pre-code': theme('colors.gray[11]'),
            '--tw-prose-pre-bg': theme('colors.gray[12]'),
            '--tw-prose-th-borders': theme('colors.gray[6]'),
            '--tw-prose-td-borders': theme('colors.gray[6]'),
            '--tw-prose-invert-body': theme('colors.gray[6]'),
            '--tw-prose-invert-headings': theme('colors.white'),
            '--tw-prose-invert-lead': theme('colors.gray[6]'),
            '--tw-prose-invert-links': theme('colors.white'),
            '--tw-prose-invert-bold': theme('colors.white'),
            '--tw-prose-invert-counters': theme('colors.gray[7]'),
            '--tw-prose-invert-bullets': theme('colors.gray[7]'),
            '--tw-prose-invert-hr': theme('colors.gray[8]'),
            '--tw-prose-invert-quotes': theme('colors.gray[11]'),
            '--tw-prose-invert-quote-borders': theme('colors.gray[8]'),
            '--tw-prose-invert-captions': theme('colors.gray[7]'),
            '--tw-prose-invert-code': theme('colors.white'),
            '--tw-prose-invert-pre-code': theme('colors.gray[6]'),
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': theme('colors.gray[7]'),
            '--tw-prose-invert-td-borders': theme('colors.gray[8]'),
            h1: {
              fontWeight: '700',
            },
            'h1 strong': {
              fontWeight: '800',
            },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('tailwindcss-debug-screens'),
  ],
}
